name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest 
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push generated snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
